name: Publish release
on:
  release:
    types: [published]
jobs:
  upload_docker:
    name: Build and upload new docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: 'us-east-1'
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: synthetic-link-detector
          REGISTRY_ALIAS: c3d4d8b6
          IMAGE_TAG: ${{ github.event.release.tag_name }}
        run: |
          docker build -t $ECR_REGISTRY/$REGISTRY_ALIAS/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$REGISTRY_ALIAS/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$REGISTRY_ALIAS/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$REGISTRY_ALIAS/$ECR_REPOSITORY:latest
  create_sam_template:
    name: creates sam template with current version
    runs-on: ubuntu-latest
    needs: upload_docker
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: create new version
        env:
          VERSION: ${{ github.event.release.tag_name }}
        run: |
          sed -i "s/<<VERSION>>/$VERSION/" "./aws/sam-template.yaml"
      - uses: actions/upload-artifact@v3
        with:
          name: sam-template.yaml
          path: ./aws/sam-template.yaml
  upload_sam_template:
    name: upload sam template
    runs-on: ubuntu-latest
    needs: [upload_docker, create_sam_template]
    strategy:
      matrix:
        aws_region:
          - 'us-east-1'
          - 'us-east-2'
          - 'us-west-1'
          - 'us-west-2'
          - 'eu-central-1'
          - 'eu-north-1'
          - 'eu-west-1'
          - 'eu-west-2'
          - 'eu-west-3'
          - 'sa-east-1'
          - 'ap-northeast-1'
          - 'ap-northeast-2'
          - 'ap-northeast-3'
          - 'ap-south-1'
          - 'ap-southeast-1'
          - 'ap-southeast-2'
          - 'ca-central-1'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: sam-template.yaml
      - name: Install aws cli
        run: |
          sudo apt-get update
          sudo apt-get install awscli
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
          aws configure set region ${{ matrix.aws_region }}
          aws s3 cp sam-template.yaml s3://logzio-aws-integrations-${{ matrix.aws_region }}/synthetic-link-detector/${{ github.event.release.tag_name }}/sam-template.yaml